### ISSUE TITLE
Can't update `spigot latest`

### ISSUE THREAD

**Issue by SilkAndSlug** [benediktschmitt/emsm#68]
This may be related to #67 .

I want to install Spigot. I'm logged in as root (`sudo -i`), but I get the same error when logged in as silkandslug.

`minecraft -s 'spigot latest' server --update` fails with:

```
error: The installation of the server 'spigot latest' failed. Installer returned with '1'.
```

The installer seems to have created a new 'spigot latest' directory inside the previous; after trying several times, I now have `/opt/minecraft/server/spigot latest/spigot latest/spigot latest/spigot latest`, which is empty.

I believe that the relevant part of the log is this:

```
[2017-02-01 22:01:07][INFO    ][argparse_                ] adding emsm arguments ...
[2017-02-01 22:01:07][INFO    ][argparse_                ] parsing arguments ...
[2017-02-01 22:01:07][INFO    ][argparse_                ] parsed arguments: Namespace(all_server=False, all_worlds=False, plugin='server', server=['spigot latest'], server_list=None, serv$
[2017-02-01 22:01:07][INFO    ][plugins                  ] running plugin 'server' ...
[2017-02-01 22:01:07][INFO    ][server                   ] Installing spigot ...
[2017-02-01 22:01:07][INFO    ][server                   ] - Building in '/tmp/spigotmcl92b4e87' ...
[2017-02-01 22:01:16][INFO    ][server                   ] - BuildTools: '/tmp/spigotmcl92b4e87/BuildTools.jar' ...
[2017-02-01 22:01:16][INFO    ][server                   ] Loading BuildTools version: git-BuildTools-0d20f9d-57 (#57)
Git name not set, setting it to default value.

[2017-02-01 22:01:16][ERROR   ][server                   ] warning: unable to access '/root/.gitconfig': Permission denied
warning: unable to access '/root/.config/git/config': Permission denied
warning: unable to access '/root/.gitconfig': Permission denied
warning: unable to access '/root/.config/git/config': Permission denied
error: could not lock config file /root/.gitconfig: Permission denied
Exception in thread "main" java.lang.RuntimeException: Error running command, return status !=0: [git, config, --global, user.name, BuildTools]
    at org.spigotmc.builder.Builder.runProcess(Builder.java:547)
    at org.spigotmc.builder.Builder.main(Builder.java:161)

[2017-02-01 22:01:16][INFO    ][server                   ] - Removing build directory /tmp/spigotmcl92b4e87
[2017-02-01 22:01:16][ERROR   ][server                   ] The installation of the server 'spigot latest' failed. Installer returned with '1'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/emsm/plugins/server.py", line 251, in _update_server
    server.reinstall()
  File "/usr/local/lib/python3.4/dist-packages/emsm/core/server.py", line 299, in reinstall
    self.install()
  File "/usr/local/lib/python3.4/dist-packages/emsm/core/server.py", line 980, in install
    raise ServerInstallationFailure(self, msg)
emsm.core.server.ServerInstallationFailure: The installation of the server 'spigot latest' failed. Installer returned with '1'.
[2017-02-01 22:01:16][INFO    ][plugins                  ] finish plugins ...
[2017-02-01 22:01:16][INFO    ][conf                     ] writing configuration ...
[2017-02-01 22:01:16][INFO    ][application              ] EMSM finished.
```

**Comment by SilkAndSlug** [comment]
In case it's relevant, `ls -al /root/.gitconfig` returns

```
-rw-r--r-- 1 root root 59 Nov  9  2014 /root/.gitconfig
```

The other [.]git[/]config files don't exist

**Comment by MarkehMe** [comment]
Weird. Why is it loading the root .gitconfig? I have this issue too. 

Even after giving the minecraft user a home and .gitconfig.. 

```
mkdir -p /home/minecraft
touch /home/minecraft/.gitconfig
chown -R minecraft:minecraft /home/minecraft
```

**Comment by benediktschmitt** [comment]
Sorry for the (very) late reply. I think the problem is the wrong environment: The EMSM changes only the *uid* and *gid* to the target user, which does not affect environment variables like *$USER*. The best solution would be  to call the EMSM always with *su* as @MarkehMe did it.

**Comment by benediktschmitt** [comment]
You could try to set *shell=True* in https://github.com/benediktschmitt/emsm/blob/fbd2b3a1e03f34913be989f4dfe49bc4b4fe2bd2/emsm/core/server.py#L962:

```Python
with subprocess.Popen(
                ["java", "-jar", buildtools],
                cwd = build_dir,
                stdout = subprocess.PIPE,
                stderr = subprocess.PIPE,
                shell = True
            ) as proc:
```

Please tell me if this works.

**Comment by SilkAndSlug** [comment]
Okay, finally got some time to try this.  :-)

I ran the following commands, making the change you suggested above. Still didn't work.  :-(

    sudo -i
    nano /usr/local/lib/python3.4/dist-packages/emsm/core/server.py
    minecraft -s 'spigot latest' server --update
    ls -aR /opt/minecraft/server/spigot\ latest

`minecraft` returned:

    spigot latest:
         reinstalling the server ...
         error: The installation of the server 'spigot latest' failed. Installer returned with '1'.

`ls` returned:

    /opt/minecraft/server/spigot latest:
        .  ..  spigot latest

    /opt/minecraft/server/spigot latest/spigot latest:
        .  ..

**Comment by gjost** [comment]
I was able to upgrade (or reinstall) after removing the `/opt/minecraft/server/spigot latest/` directory.

**Comment by SilkAndSlug** [comment]
gjost's fix didn't work for me, in v5.0.6 nor in v5.0.7b0

**Comment by SilkAndSlug** [comment]
markhughe's fix didn't work neither -- returned 1, with no output. Might be because user 'minecraft' is a no-login user.

**Comment by SilkAndSlug** [comment]
In v5.0.7b0, and logged-in as root (`sudo -i`),the logged error is now:

    [2018-01-27 23:03:05][INFO    ][argparse_                ] parsed arguments: Namespace(all_server=False, all_worlds=False, plugin='server', server=['spigot latest'], server_list=None, server_update=1, server_usage=None, worlds=[])
    [2018-01-27 23:03:05][INFO    ][plugins                  ] running plugin 'server' ...
    [2018-01-27 23:03:05][INFO    ][server                   ] Installing spigot ...
    [2018-01-27 23:03:05][INFO    ][server                   ] - Building in '/tmp/spigotmcz1pkhgdd' ...
    [2018-01-27 23:03:11][INFO    ][server                   ] - BuildTools: '/tmp/spigotmcz1pkhgdd/BuildTools.jar' ...
    [2018-01-27 23:03:11][INFO    ][server                   ] Loading BuildTools version: git-BuildTools-3346dd9-71 (#71)
    git version 2.11.0
    Git name not set, setting it to default value.
    
    [2018-01-27 23:03:11][ERROR   ][server                   ] warning: unable to access '/root/.gitconfig': Permission denied
    warning: unable to access '/root/.config/git/config': Permission denied
    warning: unable to access '/root/.gitconfig': Permission denied
    warning: unable to access '/root/.config/git/config': Permission denied
    error: could not lock config file /root/.gitconfig: Permission denied
    Exception in thread "main" java.lang.RuntimeException: Error running command, return status !=0: [git, config, --global, user.name, BuildTools]
            at org.spigotmc.builder.Builder.runProcess0(Builder.java:639)
            at org.spigotmc.builder.Builder.runProcess(Builder.java:597)
            at org.spigotmc.builder.Builder.main(Builder.java:192)
            at org.spigotmc.builder.Bootstrap.main(Bootstrap.java:23)
    
    [2018-01-27 23:03:11][INFO    ][server                   ] - Removing build directory /tmp/spigotmcz1pkhgdd
    [2018-01-27 23:03:11][ERROR   ][server                   ] The installation of the server 'spigot latest' failed. Installer returned with '1'.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/emsm/plugins/server.py", line 251, in _update_server
        server.reinstall()
      File "/usr/local/lib/python3.5/dist-packages/emsm/core/server.py", line 299, in reinstall
        self.install()
      File "/usr/local/lib/python3.5/dist-packages/emsm/core/server.py", line 1033, in install
        raise ServerInstallationFailure(self, msg)
    emsm.core.server.ServerInstallationFailure: The installation of the server 'spigot latest' failed. Installer returned with '1'.
    [2018-01-27 23:03:11][INFO    ][plugins                  ] finish plugins ...
    [2018-01-27 23:03:11][INFO    ][conf                     ] writing configuration ...
    [2018-01-27 23:03:11][INFO    ][application              ] EMSM finished.
    [2018-01-27 23:03:11][INFO    ][filelock                 ] Lock 140347026208248 released on /opt/minecraft/app.lock

**Comment by benediktschmitt** [comment]
Thanks for the hint, the *--no-login* could be a problem here. You can try to ``su -i --shell=/bin/bash minecraft`` to login as minecraft and execute emsm directly.

**Comment by SilkAndSlug** [comment]
Yep, that worked -- except my Debian doesn't have a `su -i`, so I used `su -l` instead.

**Comment by SilkAndSlug** [comment]
FWIW, updating as `minecraft`, /opt/minecraft/server/spigot\ latest/spigot\ latest is a file. Updating as `root`, produced a dir. Presumably the sub-dir collided names with the file.

**Comment by benediktschmitt** [comment]
I updated the documentation and added a link to this issue. If this problem still exists, feel free to leave a comment.

**Comment by Index-true** [comment]
After using all the fixes purposed in this post the error was still there for me, so i found some fixes : 
 * Git must be installed (might seem obvious but it's not written in the doc (or i didn't saw it)
 * minecraft user must have a home ( `usermod -d {minecraft user home dir} minecraft`) if doing update from minecraft account

I hope it can help someone :wink: 

Index
