### ISSUE TITLE
server plugin installs 1.12.1; won't install 1.12.2

### ISSUE THREAD

**Issue by SilkAndSlug** [benediktschmitt/emsm#83]
I want to start a new world, with the latest version of the Millenaire mod. Millenaire supports 1.12.2; there is _no_ version that supports 1.12.1!

EMSM has 1.12.1 installed. `minecraft -w 'minecraft forge 1.12' server --update` re-installs v1.12.1. Editing `conf/server.conf` (as below) then updating again produces _lots_ of files rather than the two jars, library dir, and tmpXNXN.log I was expecting. 

    [minecraft forge 1.12]
    url=https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/minecraft_server.1.12.2.jar

What did I do wrong? Is there an example of correct config we can add to the docs?

**Comment by SilkAndSlug** [comment]
Changing that config to

    [minecraft forge 1.12]
    url=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2768/forge-1.12.2-14.23.5.2768-universal.jar

produces all the necessary files -- but in a subdirectory i.e.

    server/minecraft\ forge\ 1.12/minecraft\ forge\1.12/

not
 
    server/minecraft\ forge\ 1.12/

But the client still refuses to connect, with error: `Outdated server! I'm still on 1.12`

Presumably the server is advertising it's running 1.12, not 1.12.2. Is that likely? How would I fix it?

**Comment by SilkAndSlug** [comment]
... and when I deleted the `server/minecraft forge 1.12/` directory and re-ran the updater, it failed with this message:

    EMSM: Uncaught exception:
     > Exception: ServerInstallationFailure
     > Module     /usr/local/lib/python3.5/dist-packages/emsm/core/server.py
     > Message:   The installation of the server 'minecraft forge 1.12' failed. The installation of the server 'minecraft forge 1.12' failed. Installer returned with '1'.
     > A full traceback can be found in the log file.

The log file ends:

[2019-06-03 00:40:04][INFO    ][worlds                   ] initialising world 'pokeworld' ...
[2019-06-03 00:40:18][INFO    ][server                   ]
[2019-06-03 00:40:18][WARNING ][server                   ] We appear to be missing one or more essential library files.
You will need to add them to your server before FML and Forge will run successfully.java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:52)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)

[2019-06-03 00:40:18][ERROR   ][application              ] uncaught exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/emsm/core/server.py", line 771, in install
    raise ServerInstallationFailure(self, msg)
emsm.core.server.ServerInstallationFailure: The installation of the server 'minecraft forge 1.12' failed. Installer returned with '1'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/emsm/__init__.py", line 41, in run
    app.setup()
  File "/usr/local/lib/python3.5/dist-packages/emsm/core/application.py", line 329, in setup
    self._worlds.load_worlds()
  File "/usr/local/lib/python3.5/dist-packages/emsm/core/worlds.py", line 870, in load_worlds
    world = WorldWrapper(self._app, name)
  File "/usr/local/lib/python3.5/dist-packages/emsm/core/worlds.py", line 256, in __init__
    self._server.install()
  File "/usr/local/lib/python3.5/dist-packages/emsm/core/server.py", line 773, in install
    raise ServerInstallationFailure(self, err) from err
emsm.core.server.ServerInstallationFailure: The installation of the server 'minecraft forge 1.12' failed. The installation of the server 'minecraft forge 1.12' failed. Installer returned with '1'.
[2019-06-03 00:40:18][INFO    ][application              ] EMSM finished.
[2019-06-03 00:40:18][INFO    ][filelock                 ] Lock 140338598057576 released on /home/emsm/app.lock

**Comment by SilkAndSlug** [comment]
Sorted it. The server plugin (via conf/server.conf) expects the 'installer' jar, i.e. 

    [minecraft forge 1.12]
    url = http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2768/forge-1.12.2-14.23.5.2768-installer.jar

The fix is, I presume, to update line #877 of `core/server.py`

**Comment by SilkAndSlug** [comment]
Updated, and pushed to GitHub. Just waiting for PyPi login from @benediktschmitt
